name: Build TA-Lib wheels for Linux

on:
  workflow_dispatch:

env:
  TALIB_C_VER: 0.6.2
  TALIB_PY_VER: 0.6.0
  PIP_NO_VERIFY: 0
  PIP_VERBOSE: 1
  CIBW_BUILD_VERBOSITY: 2
  CIBW_BEFORE_BUILD: pip install -U setuptools wheel numpy Cython
  CIBW_TEST_REQUIRES: pytest pandas polars
  CIBW_TEST_COMMAND: >
    cd .. &&
    pytest --rootdir=C: -k "not RSI and not threading" {project}/tests
  CIBW_TEST_SKIP: "*win32 cp37* cp38* cp39*"
  CIBW_SKIP: "pp* cp36*"

jobs:
  build_x86_64:
    name: Build Linux x86_64 wheels
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - run: build_linux.sh
        shell: bash
      - uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS_LINUX: AMD64
          CIBW_ENVIRONMENT_LINUX : >
            TA_LIBRARY_PATH="/usr/local/lib/ta-lib;$LIB"
            TA_INCLUDE_PATH="/usr/local/include/ta-lib;$INCLUDE"
            PIP_NO_BUILD_ISOLATION=false
      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: wheels-linux-x64
